export const SG_DISTRICTS = [
  { value: "D01", label: "D01 — Boat Quay / Raffles Place / Marina" },
  { value: "D02", label: "D02 — Chinatown / Tanjong Pagar" },
  { value: "D03", label: "D03 — Alexandra / Commonwealth" },
  { value: "D04", label: "D04 — Harbourfront / Telok Blangah" },
  { value: "D05", label: "D05 — Buona Vista / West Coast / Clementi" },
  { value: "D06", label: "D06 — City Hall / Clarke Quay" },
  { value: "D07", label: "D07 — Beach Road / Bugis / Rochor" },
  { value: "D08", label: "D08 — Farrer Park / Serangoon Rd" },
  { value: "D09", label: "D09 — Orchard / River Valley" },
  { value: "D10", label: "D10 — Tanglin / Holland / Bukit Timah" },
  { value: "D11", label: "D11 — Newton / Novena" },
  { value: "D12", label: "D12 — Balestier / Toa Payoh" },
  { value: "D13", label: "D13 — Macpherson / Potong Pasir" },
  { value: "D14", label: "D14 — Eunos / Geylang / Paya Lebar" },
  { value: "D15", label: "D15 — East Coast / Marine Parade" },
  { value: "D16", label: "D16 — Bedok / Upper East Coast" },
  { value: "D17", label: "D17 — Changi Airport / Loyang" },
  { value: "D18", label: "D18 — Tampines / Pasir Ris" },
  { value: "D19", label: "D19 — Serangoon Garden / Hougang / Punggol" },
  { value: "D20", label: "D20 — Bishan / Ang Mo Kio" },
  { value: "D21", label: "D21 — Upper Bukit Timah / Clementi Park / Ulu Pandan" },
  { value: "D22", label: "D22 — Jurong / Boon Lay / Tuas" },
  { value: "D23", label: "D23 — Hillview / Dairy Farm / Bukit Panjang / Choa Chu Kang" },
  { value: "D24", label: "D24 — Lim Chu Kang / Tengah" },
  { value: "D25", label: "D25 — Kranji / Woodgrove" },
  { value: "D26", label: "D26 — Upper Thomson / Springleaf" },
  { value: "D27", label: "D27 — Yishun / Sembawang" },
  { value: "D28", label: "D28 — Seletar / Yio Chu Kang" },
] as const;
